### PR TITLE
Home page styles

### PR DESCRIPTION
**Pull request by harrygfox**
At time of Draft:
- home done, but not entirely responsive
- quiz done, but to limits of app (correct/incorrect feedback, different styles for different quiz size) and not entirely responsive
- nothing done on end game screen
- included and linked a normalise.css
- CSS file undergone mid-day review - needs another for bloat

Open questions around 
1. functionality
2. responsive behaviour

### CODE REVIEW

**Comment by Jbarget** [comment]
on the homepage you have to scroll to see all the relevant content, i reckon reducing vertical margin/padding would be good so it all fits in the window

**Comment by harrygfox** [comment]
@Jbarget your [comment above ](https://github.com/Jbarget/guess-who/pull/2#issuecomment-466981695) should be addressed by [the latest commit](https://github.com/Jbarget/guess-who/pull/2/commits/9046017b613431415a7ab10cc0401a85752e726b)

**Comment by harrygfox** [comment]
This is a basic version of the entire designs and is ready to be merged pending a review.

Things that have not been included:
- [x] check mark icons (on correct answers)
- [x] cross icons (on incorrect answers)
- [x] tests on smaller screens (estimated to break in a couple of minor places around sub-767px)
- [x] css review - removing bloat

**Review by harrygfox — COMMENTED** [review]
Ahhhh nice

**Comment by harrygfox** [comment]
everything's good - the design starts to break sub 600px

**Pull request merged**
